Repository carlossg-org/environment-biterfir-staging, pull requests merged in 2019-01, with the labels that each got.

#4 croc-hunter-jenkinsx to 0.0.102
  env/requirements.yaml
Labels: size/S

#3 croc-hunter-jenkinsx to 0.0.101
  env/requirements.yaml
Labels: size/XS

#5 Update exposecontroller
  env/requirements.yaml
Labels: size/XS

#6 fix exposecontroller config
  env/values.yaml
Labels: ok-to-test, size/S

#7 Rollback croc-hunter
  env/requirements.yaml
Labels: size/XS
